# Generated by Django 4.2.7 on 2025-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], default='citizen', max_length=15),
        ),
    ]
