# Generated by Django 4.2.7 on 2025-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('superadmin', 'Super Administrateur')], default='citizen', max_length=15),
        ),
    ]
